{
 "title": "Spark Job Metrics",
 "tags": [
  "job",
  "spark-metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Spark Job" },
   {
    "name": "application_id",
    "label": "Application ID",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total{namespace=\"iomete-system\", pod=\"${job}-driver\"}, application_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(metrics_executor_memoryUsed_bytes{\n  namespace=\"iomete-system\", \n  executor_id!=\"driver\", \n  application_id=\"$application_id\"\n}) by (executor_id, application_id))\nby (application_id)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{\n    namespace=\"iomete-system\", \n    executor_id!=\"driver\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n})"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_failedTasks_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\", \n    executor_id!=\"driver\"\n})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n})"
    }
   ]
  },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalDuration_seconds_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Tasks per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalTasks_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleRead_bytes_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleWrite_bytes_total{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\",  \n    application_id=\"$application_id\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{\n    namespace=\"iomete-system\", \n    pod=\"${job}-driver\", \n    application_id=\"$application_id\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  }
 ]
}